### ISSUE TITLE
Fotmat code lại đi em

### ISSUE THREAD

**Issue by quocthinhvo** [kodesupporter/kodesupporter.github.io#1]
Em cần format code tốt thì nhiều người mới có thể hỗ trợ em nhé. Thêm cả comment cho từng function.
Và anh nghĩ em cần chia ra các tệp CSS, JS riêng, làm vậy cho dễ quản lí.

**Comment by kodesupporter** [comment]
Em chỉnh lại rồi nha, anh thử xem

**Comment by quocthinhvo** [comment]
Tốt đó em. Anh đóng issues này
